export enum ALL_ROUTES {
  HOMEPAGE = '/',
  TERMS_OF_SERVICE = '/terms-of-service',
  DESIGN_YOUR_OWN = '/design-your-own',
  FAQ = '/faq',
  RETURNS = '/returns',
  SHIPPING = '/shipping',
  MEDIA = '/media',
  SUSTAINABILITY = '/sustainability',
  COOKIE_SETTINGS = '/cookie-settings',
  PRIVACY_POLICY = '/privacy-policy',
  CONTACT_US = '/contact-us',
  PRODUCTS = '/products',
  CUSTOMER_REVIEWS = '/products/customer-reviews',
  MY_JOURNEY = '/my-journey',
  SOCIALS = '/my-socials',
  PROFILE = '/profile',
  ADDRESS = '/address',
  ORDERS = '/orders',
  NOTIFICATIONS = '/notifications',
  OUR_STORY = '/our-story',
  ORDER_SUCCESS = '/order-success',
  LOGIN_UI = '/admin/login',
  ADMIN_DASHBOARD = '/admin/dashboard',
  ORDER_LISTING = '/order-listing',
  ORDER_DETAIL = '/orderDetail/:orderId',
}
// reset password route to have :tokenId in route
